// Downloads self-hosted .woff2 fonts (latin + latin-ext only) into site/assets/fonts
// and writes the matching @font-face rules to site/assets/css/fonts.css.
// Run: node _tools/fetch-fonts.js
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', 'site');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');
const CSS_OUT = path.join(ROOT, 'assets', 'css', 'fonts.css');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

// Each entry is fetched separately. Italic is a static 300 cut (~40 KB vs ~236 KB variable with opsz).
const REQUESTS = [
  'family=Newsreader:opsz,wght@6..72,200..500',
  'family=Newsreader:ital,wght@1,300',
  'family=Hanken+Grotesk:wght@300..600&family=IBM+Plex+Mono:wght@400;500',
];
const KEEP = new Set(['latin', 'latin-ext']);

(async () => {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  let css = '';
  for (const q of REQUESTS) {
    css += await (await fetch('https://fonts.googleapis.com/css2?' + q + '&display=swap', { headers: { 'User-Agent': UA } })).text();
  }
  const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)];
  let out = '/* Self-hosted fonts (SIL Open Font License 1.1). Generated by _tools/fetch-fonts.js */\n';
  for (const [, subset, block] of blocks) {
    if (!KEEP.has(subset)) continue;
    const family = block.match(/font-family: '([^']+)'/)[1];
    const style = block.match(/font-style: (\w+)/)[1];
    const src = block.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${style}-${subset}.woff2`;
    const weight = block.match(/font-weight: ([\d ]+);/)[1];
    // Static families (Plex Mono) come as one file per weight
    const name = /\d+ \d+/.test(weight) ? file : file.replace('.woff2', `-${weight}.woff2`);
    const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
    fs.writeFileSync(path.join(FONT_DIR, name), buf);
    out += '\n/* ' + subset + ' */\n' + block.replace(src, '../fonts/' + name) + '\n';
    console.log(name, (buf.length / 1024).toFixed(1) + ' KB');
  }
  fs.writeFileSync(CSS_OUT, out);
})();
